### ISSUE TITLE
Something About Zdock results

### ISSUE THREAD

**Issue by yymyymyym** [lightdock/membrane_docking#2]
There is a clustering procedure in membrane docking, but no clustering for Zdock. So the comparision maybe not fair in the paper. How do you think about this?

**Comment by brianjimenez** [comment]
Clustering in LightDock is intra-swarm and not inter-swarm, which means that several similar structures are to be found in the final pool of predictions as neighboring swarms might score similar and predict poses in the same binding location. Said so, the clustering method used by ZDOCK (referred as `pruning` as in [[1]](https://onlinelibrary.wiley.com/doi/full/10.1002/prot.22764)) depends on a user selected threshold which, to our knowledge, has not been disclosed. Additionally, it seems there is no clustering mechanism implemented in the ZDOCK server so far (https://academic.oup.com/bioinformatics/article/30/12/1771/381628).
Please don't hesitate to reopen the issue if you have any other question about the protocol.

**Comment by amjjbonvin** [comment]
As an additional comment, I think it is good practice to actually reveal your identify when commenting / opening issues (your username @yymyymyym is rather cryptic...) . Open science is not only about data / software, but also about  the discussion around it.
